version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/dashboard
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - rabbit
      - pgdb
      - worker

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=dashboard
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    ports:
      - "5432:5432"
    #superuser: admin password:admin
    #Email address: admin@smthng.com

  rabbit:
    image: rabbitmq:latest

  redis:
    image: redis
    ports:
      - "6379:6379"

    # Celery worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A dashboard worker -l INFO
    volumes:
      - .:/dashboard
    depends_on:
      - redis
      - rabbit
      - pgdb