# Generated by Django 3.2.6 on 2021-08-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=10)),
                ('graph', models.CharField(max_length=10)),
                ('interval', models.IntegerField(default=1)),
                ('step', models.IntegerField(default=1)),
                ('date', models.DateTimeField(default=1)),
            ],
        ),
    ]
