# Generated by Django 3.2.6 on 2021-08-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func_modeling', '0002_alter_function_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='graph',
            field=models.ImageField(upload_to=''),
        ),
    ]
