# Generated by Django 3.2.6 on 2021-08-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func_modeling', '0004_auto_20210821_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='graph',
            field=models.ImageField(blank=True, default='default.jpg', help_text='150x150px', upload_to=''),
        ),
        migrations.AlterField(
            model_name='function',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
